# can use variables like {build} and {branch}
version: 1.2.{build}

branches:
  only:
    - develop

configuration:
  - Debug
  - Release

environment:
  matrix:
    - VS_VERSION_MAJOR: 12
    - VS_VERSION_MAJOR: 14

platform:
  - Win32
  - x64

before_build: "scripts\\appveyor.bat"

build:
  parallel: true
  project: build/cereal.sln
  verbosity: minimal

test_script: "scripts\\appveyor.bat test"

artifacts:
  - path: build\Testing
  - path: out
